/***************************************************************************
// (c) 2016  Andrews Consulting
//
// Description    	: Class to facilitate Trailhead training
//                  
// 06 Jan 2016		: Initial Implementation
//***************************************************************************/
@isTest
private class ContactSearch_Test {

	@isTest Static void unitTest1() {
			ContactSearch.searchForContacts('Black','20000');


	}
}