/***************************************************************************
// (c) 2016  Andrews Consulting
//
// Description    	: Test Class
//                  
// 06 Jan 2016		: Initial Implementation
//***************************************************************************/
@isTest
private class StringArrayTest_Test {

    @isTest static void UnitTest1() {
        
        List<String> testobject1 = StringArrayTest.generateStringArray(1);
        }
}